In [5]:
# Initialize 
import pandas as pd
import importlib, signifier_analysis
importlib.reload(signifier_analysis)

# if you want to compute embeddings locally
# import CLASS YAP BERT_EMBEDDINGS_MW'YI 

# import Signifier_Analyzer 
from signifier_analysis import SignifierAnalyzer

# display warnings
from IPython.display import display, HTML
import warnings

# enable scrolling in large outputs
def show_scroll(df, height=400):
    display(HTML(f'<div style="height:{height}px; overflow:auto">{df.to_html()}</div>'))

pd.set_option("display.max_rows", 200)       # kaç satır göstersin
pd.set_option("display.max_colwidth", None)  # left/right kırpılmasın
warnings.filterwarnings("ignore", category=UserWarning)

In [7]:
from sklearn.metrics import normalized_mutual_info_score

first = meta["surface"].str.split(" | ").str[0].apply(tr_lower)
meta["suffix"] = first.str.replace(r"^millet", "", regex=True)

print(normalized_mutual_info_score(meta["suffix"], meta["cluster"]))
pd.crosstab(meta["cluster"], meta["suffix"], normalize="index").round(2)

NameError: name 'meta' is not defined

# 1.Analysis: Semantic Clusters of 
## **MİLLET** ***(the nation)***

In [3]:
millet = SignifierAnalyzer("millet", version="maskwhite")
#millet.n_component_sensitivity(version="maskwhite")   # sensitivity analysis for maskwhite vectors; picked -> nc = 10, clusters = 128, noise = 22.8% 
                                                   # looking for: the cluster with relatively high number of clusters and low noise 
millet.fit(n_components=20, ranking="both", max_df_ratio = 1, dim_ratio=0.85, hide_common=True, top_words=100, root_len=5, min_word_len=3)

millet | venue=hepsi | n=9363 | faz: {1: np.int64(1556), 2: np.int64(2199), 3: np.int64(5608)}
number of clusters: 123 | noise: 24%
c94 n=  31
   freq: hesabını(41; 41), ·millete(41; 37), kuruşun(37; 34), harcadığınız(35; 25), para(29; 9), vereceksiniz(29; 22), başkanı(18; 6), belediye(17; 12), söyledim(14; 8), yaptım(12; 6), halka(10), hizmet(8), ayrımcılık(7), vatandaş(7), vergi(7), anlayışını(6), hesap(6), siyaset(6), vermedi(6), belde(5), götürün(5), herkese(5), yeni(5), eşit(4), harcıyor(4), ikinci(4), olacağız(4), verin(4), verirseniz(4), yapmayacaksınız(4), yatırımın(4), adam(3), başlatan(3), bütçe(3), büyük(3), demokrasinin(3), evet(3), günahsa(3), hakkı(3), istiyoruz(3), kemal(3), kimseyi(3), kucaklayacaksınız(3), kul(3), saygı(3), söz(3), yaparsanız(3), yapılacaktır(3), aldığınız(2), arkadaşlarımda(2), bay(2), dedim(2), destek(2), dikilmek(2), duyduğunuz(2), fakir(2), geliyoruz(2), genel(2), getirebilirsiniz(2), güven(2), havalimanı(2), ilkelerde(2), istedim(2), içinde(2), kaça(2), kesinlikle(2), kitabımızda(2), kılıçdaroğlu(2), milyona(2), olmazsa(2), saraylarda(2), saydam(2), son(2), söylüyorum(2), veren(2), veriyor(2), yapacaksanız(2), yemek(2), yoktur(2), çıkış(2), ödedikleri(2), ödüyor(2), önemli(2), adalet(1), adına(1), ahlaklı(1), aldı(1), alınacak(1), alıyorsunuz(1), andan(1), anlatıyorsun(1), anılırsınız(1), aradığım(1), aralamış(1), arasında(1), arkasında(1), atıldı(1), açılım(1), açın(1), açıyoruz(1)
   ctfidf: hesabını(41; 41), kuruşun(34; 34), vereceksiniz(29; 22), harcadığınız(25; 25), para(20; 9), belediye(12; 12), söyledim(8; 8), yaptım(6; 6), hesap(6; 6), siyaset(6), başkanı(6), ayrımcılık(5), anlayışını(5), hizmet(5), yeni(5)
   verbs:
c89 n=  49
   freq: parayı(56; 16), ·millete(53; 52), getireceğim(48; 39), vereceğim(45; 36), tamamını(28; 25), son(24; 24), kuruşuna(21; 18), götürdükleri(17; 4), kemal(15; 15), bay(14; 14), biliyorum(14), dolar(14), söz(14), çeteler(10), türkiye(9), banka(8), beşli(8), endişe(7), hakkı(7), sanıyorlar(7), sarayı(7), yurtdışına(7), alacağım(6), devleti(6), emin(6), etmeyin(6), gelirse(6), gönderiyorlar(6), kılıçdaroğlu(6), lira(6), olun(6), alıp(5), amerika(5), cumhurbaşkanı(5), edeceğim(5), hortumları(5), kaçırdıkları(5), londra(5), sentine(5), verilen(5), yemezler(5), diyorlar(4), düşüncem(4), görmeyecek(4), güzel(4), harcanan(4), hesabın(4), istemez(4), kazandığı(4), keseceğim(4), seyredecek(4), size(4), vakıf(4), vermediler(4), yatırdıklarını(4), yılda(4), ülkede(4), bağlanan(3), başkanı(3), chp(3), dışarıya(3), dışına(3), etmesin(3), garantisi(3), gökdelene(3), hepsini(3), istiyorum(3), kaç(3), kaçak(3), komisyon(3), konuştum(3), lider(3), söyledi(3), veriyorlar(3), yurt(3), adalet(2), adayı(2), afyon(2), aittir(2), aldık(2), alın(2), arkadaşlar(2), artık(2), asla(2), atatürk(2), baronları(2), başka(2), birilerine(2), bitmemiş(2), bugüne(2), bunlara(2), büyüdü(2), cebi(2), coğrafyada(2), dedim(2), derse(2), diyecek(2), dünyanın(2), ekrem(2), emekli(2)
   ctfidf: parayı(47; 16), getireceğim(39; 39), vereceğim(36; 36), tamamını(25; 25), son(24; 24), kuruşuna(18; 18), kemal(15; 15), bay(14; 14), söz(13; 8), biliyorum(12), dolar(11), türkiye(9), beşli(8), yurtdışına(7), sanıyorlar(7), endişe(6), emin(6), lira(6), olun(6), kılıçdaroğlu(6), sentine(5), londra(5), alacağım(5), amerika(5), alıp(5)
   verbs:
c30 n=  25
   freq: ·milletin(27; 26), önüne(20; 20), insan(9; 4), sorunu(9; 3), çıkıp(9; 9), dolar(8; 6), kardeşim(7; 7), bekleyin(6; 4), erdoğan(6; 4), güven(6; 3), istiyorsan(6), açıklasın(5), değerli(5), karşısına(5), artık(4), demokrasiyi(4), devlet(4), fedakarlık(4), kaçan(4), proje(4), söylüyorum(4), televizyona(4), yeter(4), çıkacaksın(4), çıkalım(4), ülkede(4), baharı(3), bırak(3), diyeceksin(3), diyorsunuz(3), evet(3), gerçekten(3), parasını(3), sabretmiyorsun(3), sandığı(3), strateji(3), tasarruf(3), vermek(3), yalan(3), yöneten(3), çözeceğiz(3), alanlar(2), anlatayım(2), ayıracaksın(2), basın(2), başarılı(2), başka(2), belirlemek(2), bey(2), bilsin(2), bulunacak(2), bulursan(2), dersiniz(2), dinleye(2), doğalgaz(2), ederim(2), ekonomide(2), gerekçelerle(2), getirirseniz(2), güzel(2), halini(2), halkıma(2), hayır(2), hepinize(2), isterim(2), içinde(2), içine(2), karar(2), katlanıyor(2), kesiliyor(2), kişi(2), komedi(2), korkak(2), korkuyorsun(2), kullananlar(2), mahkemede(2), mensupları(2), milli(2), milyonlarca(2), papazı(2), perişan(2), seslenmek(2), sindirememiş(2), siyasette(2), söylememektir(2), tabloyla(2), terörist(2), teşekkür(2), tutuksuz(2), türkiye(2), yapıyorsunuz(2), yargılama(2), yerli(2), çete(2), çocuk(2), çıkarsınız(2), çıksın(2), çıktılar(2), önünde(2), ahlakın(1)
   ctfidf: önüne(20; 20), çıkıp(9; 9), kardeşim(7; 7), dolar(6; 6), değerli(5; 5)
   verbs:
c51 n=  46
   freq: ·milletin(119; 103), kararı(55; 34), azim(52; 52), amasya(44; 40), istiklalini(40; 36), kurtaracaktır(36; 32), tamimi(20; 8), demokrasiyi(18; 10), iradesi(13; 9), kemal(13; 13), halkın(11), anayasa(10), getirecektir(10), mustafa(10), belirleyecektir(9), diyor(9), milli(9), cumhuriyet(8), ülkeye(8), anlamda(7), gazi(7), genel(7), güvendi(7), kişinin(7), kurtuluş(7), mahkemesine(7), sözüm(7), atatürk(6), dedik(6), geleceğini(6), gerçek(6), kongresi(6), osmanlı(6), sahip(6), vardır(6), adamın(5), bahar(5), dediler(5), der(5), egemenliğini(5), evet(5), hepinize(5), ittifakı(5), kaderini(5), mücadelenin(5), olacaktır(5), sandığa(5), savaşı(5), söyler(5), sözcüğü(5), türkiye(5), yanlıştır(5), yoktur(5), çanakkale(5), beraber(4), edilmiş(4), geldiğinde(4), geçilmez(4), gitti(4), ifade(4), padişah(4), partisi(4), saygı(4), vatanın(4), yapılacak(4), yer(4), önemlidir(4), adam(3), anadolu(3), arkasından(3), bağımsızlık(3), başka(3), başlangıcıdır(3), belge(3), cümle(3), darbe(3), dedi(3), değerli(3), erzurum(3), güçlüdür(3), insanların(3), işgal(3), kavramı(3), kullanacaksınız(3), kürsüden(3), milletvekili(3), rejimi(3), saray(3), sivas(3), son(3), sıfatıyla(3), tanımlayamayız(3), tehlikededir(3), yoldaş(3), yılında(3), şekilde(3), şudur(3), alır(2), anladığımız(2), arasında(2)
   ctfidf: azim(52; 52), kararı(46; 34), amasya(40; 40), istiklalini(36; 36), kurtaracaktır(32; 32), tamimi(16; 8), kemal(13; 13), demokrasiyi(10; 10), mustafa(10; 10), iradesi(9), kişinin(7), anayasa(7), gazi(7), kongresi(6), osmanlı(6), anlamda(6), vardır(6), atatürk(6), milli(6), dedik(6), sahip(6), cumhuriyet(6), belirleyecektir(5), kaderini(5), yanlıştır(5), çanakkale(5), kurtuluş(5), der(5), dediler(5), sandığa(5), gerçek(5), ittifakı(5), yoktur(5), halkın(5), evet(5), türkiye(5)
   verbs:
c37 n=  34
   freq: ·milletin(41; 37), aklıyla(32; 32), alay(27; 27), kuyruğu(21; 7), varlık(15; 14), ediyorlar(12; 9), diyor(8; 5), parti(8; 3), etmektir(7; 4), gerçekten(7; 4), siyasettir(6), soğan(6), adı(5), allah(5), alıyoruz(5), ettiler(5), güçlü(5), memleketi(5), söyler(5), dalga(4), olacak(4), söylüyorum(4), türkiye(4), yılın(4), örgütü(4), adına(3), aklını(3), başkanı(3), bilmez(3), cumhuriyet(3), değişikliği(3), enflasyon(3), geçiyor(3), gideceğiz(3), günde(3), hepimize(3), iktidar(3), meclis(3), muhafazakar(3), mısır(3), net(3), olabilir(3), sandığa(3), vatandaş(3), vicdanını(3), yazık(3), ücret(3), ülke(3), alınmadı(2), anayasa(2), anlamakta(2), anlatarak(2), arkadaşlar(2), başına(2), belirlenmesi(2), biliyoruz(2), büyük(2), bırak(2), davası(2), dem(2), demektir(2), destek(2), devam(2), düşüyor(2), elde(2), evet(2), ferasetini(2), fikri(2), gazze(2), gelmeden(2), genel(2), geziyorsun(2), gittik(2), görev(2), görmeyi(2), görüyor(2), günahtır(2), hakaret(2), halk(2), hallere(2), hatalar(2), huzur(2), ihtimalde(2), inanıyor(2), isteğim(2), içinde(2), kahramanlık(2), kemal(2), küçümseyen(2), kızıyordu(2), lira(2), madde(2), olgunlaşmış(2), oynuyorsun(2), oğlum(2), pahalılığı(2), parlamento(2), pkk(2), sisi(2), sokacaklar(2)
   ctfidf: aklıyla(32; 32), alay(27; 27), kuyruğu(14; 7), varlık(14; 14), ediyorlar(9; 9), ettiler(5; 5), adı(5; 5), güçlü(5; 5), allah(5; 5), diyor(5)
   verbs:
c93 n=  84
   freq: hesabını(103; 103), ·millete(100; 89), kuruşun(74; 62), vermek(67; 36), harcadığı(58; 8), siyaset(40; 18), verginin(40; 13), halk(34; 12), para(33; 8), devleti(26; 14), belediye(25), yöneten(24), toplanan(22), başkanlarımız(21), lazım(21), demektir(18), istiyoruz(16), onurlu(16), anlayış(15), cumhuriyet(13), hesap(13), partili(13), vatandaştan(13), ödediği(13), demokrasinin(12), iktidar(12), temel(12), vereceğiz(12), insan(11), türkiye(11), veren(11), ahlaklı(10), harcıyorsa(10), verdiğiniz(10), verir(10), ülkeden(10), budur(9), hakkı(9), sizlerin(9), veriyim(9), diyor(8), güzel(8), kul(8), görev(7), hizmet(7), vermiyorsa(7), yaptılar(7), yeni(7), değerli(6), gelir(6), kural(6), sevgisi(6), yapıyorlar(6), çalışıyorlar(6), ödüyorsunuz(6), dünya(5), edeceğiz(5), geldik(5), geleneği(5), gereken(5), gereğidir(5), israfa(5), kaynağı(5), memlekete(5), nedir(5), son(5), tarih(5), yapmadan(5), adalet(4), ayrım(4), belde(4), borcudur(4), bulunduysam(4), etmek(4), fabrikalar(4), felsefemizde(4), getireceğiz(4), içinde(4), katılacaksınız(4), liyakat(4), namus(4), söyledim(4), temiz(4), uçak(4), yapacağız(4), yatırımın(4), yaşamak(4), yoktur(4), ödersiniz(4), şerefli(4), adaylarımız(3), anlatmamız(3), bayrak(3), beklediği(3), beraber(3), bilmiyor(3), borçlarını(3), boynumuzun(3), bütçenin(3), büyük(3)
   ctfidf: hesabını(103; 103), kuruşun(68; 62), vermek(42; 36), harcadığı(34; 8), siyaset(33; 18), verginin(30; 13), belediye(22; 22), lazım(21; 21), toplanan(19; 14), demektir(18), halk(18), devleti(14), hesap(13), para(13), temel(11), veren(11), cumhuriyet(11), türkiye(11), yöneten(10), ödediği(9), budur(9), kul(8), güzel(8), harcıyorsa(7), ahlaklı(7), hakkı(7), istiyoruz(7), yeni(7), onurlu(6), başkanlarımız(6), vereceğiz(6), demokrasinin(6), hizmet(6), iktidar(6), değerli(6), vatandaştan(5), sizlerin(5), nedir(5), gelir(5), partili(5), son(5)
   verbs:
c102 n=  54
   freq: ·millete(66; 55), sözüm(52; 30), borcudur(15; 7), biliyorum(14; 9), iktidar(13; 10), allah(12; 12), getireceğim(12; 3), içinde(11; 11), yapacağız(11; 7), hakkı(9; 5), türkiye(9), doları(8), nasip(8), olduğumuzda(8), verdim(8), yıkılan(8), alacağım(7), asla(7), eder(7), hafta(7), kuruşu(7), memlekete(7), siyaset(7), söyledim(7), çalışmaları(7), çetenin(7), beşli(6), devlet(6), edeceğiz(6), götürdüler(6), istiyorum(6), mücadele(6), namus(6), paraların(6), suriyeli(6), vereceğim(6), yıl(6), ülkelerine(6), askeri(5), atatürk(5), baronların(5), cumhuriyet(5), sizlerin(5), süleyman(5), tamamını(5), uyuşturucu(5), yapıldı(5), üzerinden(5), amerika(4), bilmiyoruz(4), bitmemiş(4), diyor(4), evde(4), geç(4), görev(4), kardeşlerimizi(4), olacak(4), oylarıyla(4), parti(4), teğmenlerine(4), topraklara(4), türbesini(4), tüyü(4), vatan(4), yapanlar(4), yetimin(4), şah(4), afganların(3), ahırı(3), alıp(3), başkanlarımız(3), beraber(3), boynumun(3), demokrasiyi(3), doğruları(3), döndü(3), dünyalıklarını(3), evet(3), fazla(3), felaketi(3), günah(3), haksız(3), halk(3), hava(3), hepimizin(3), herkesi(3), huzur(3), insan(3), işsiz(3), karşıyayız(3), kemal(3), kimlik(3), kul(3), limanını(3), mustafa(3), sayısını(3), sorunu(3), tarih(3), tekrar(3), teslim(3)
   ctfidf: sözüm(46; 30), allah(12; 12), içinde(11; 11), iktidar(10; 10), biliyorum(9; 9), türkiye(9; 9), olduğumuzda(8; 8), nasip(8; 8), borcudur(7; 7), eder(7), hafta(7), yapacağız(7), asla(7), doları(6), beşli(6), verdim(6), yıl(6), yıkılan(5), namus(5), süleyman(5), tamamını(5), hakkı(5), atatürk(5)
   verbs:
c61 n=  25
   freq: ·milletine(31; 8), güveniyoruz(14; 7), halkına(13; 4), seviyorum(11; 8), düşüneceğiz(10; 5), bayrağımı(7; 3), devletine(7; 3), diyor(7; 6), vatanımı(7; 4), ülkenin(7; 3), cumhurbaşkanı(5), lazım(5), sevdiğim(5), siyaset(5), anlatmak(4), evet(4), karar(4), korkan(4), türkiye(4), yoktur(4), amerikan(3), başka(3), başkanı(3), cumhuriyeti(3), cumhurun(3), destek(3), egemenlik(3), götürmek(3), hizmet(3), insanlara(3), olacak(3), seven(3), sizler(3), vermedim(3), vicdan(3), yeri(3), adam(2), ahlak(2), arasına(2), araştıracağım(2), atatürk(2), bağlılığına(2), başbakanı(2), başında(2), belediye(2), bizler(2), dedi(2), dediği(2), demokrasiye(2), doğruları(2), geldim(2), gelen(2), gerçek(2), geçirdi(2), harcadığı(2), hepimiz(2), hesabını(2), hesap(2), hükümetin(2), istiyorum(2), kayıtsız(2), kişiyi(2), korkuyor(2), kullanacağız(2), malvarlığımı(2), memleketim(2), meşruiyet(2), milletvekili(2), olabilir(2), olay(2), reistir(2), sahibi(2), sesleniyorum(2), suriyelileri(2), söylemezse(2), temiz(2), toprakları(2), torunlarımızı(2), vatandaşın(2), veremeyeceğim(2), veren(2), yapıyorlar(2), çocuklarımızı(2), çıktım(2), özgürce(2), üzerinde(2), şartsız(2), şirketine(2), afganları(1), akp(1), alacağı(1), aldım(1), alttaki(1), alıp(1), alır(1), anayasa(1), anda(1), anlayışınızı(1), arkadaşlar(1), artık(1)
   ctfidf: seviyorum(8; 8), güveniyoruz(7; 7), diyor(6; 6), sevdiğim(5; 5), düşüneceğiz(5; 5)
   verbs:
c80 n=  25
   freq: ·milleti(28; 22), paraları(12; 5), alacağım(11; 8), çetelerden(11; 5), götüreceksin(10; 6), beşli(9; 9), devleti(9; 5), diyor(6; 3), hikaye(6; 3), kemal(6; 6), lazım(6), olacak(6), soyan(6), lira(5), soydular(5), soyulmasını(5), alan(4), amerika(4), anlatın(4), bay(4), beslendiğini(4), biliyorum(4), fitil(4), hakkını(4), istemem(4), memnun(4), seyredecek(4), soyup(4), tamamını(4), vermek(4), yeter(4), çevirdin(4), çıkaracağız(4), ülke(4), artık(3), bitmemiş(3), bunlara(3), büyük(3), cambaza(3), dolarla(3), dünyanın(3), endişe(3), getireceğim(3), halktan(3), kardeşim(3), sensin(3), soyacaksın(3), soymak(3), soğana(3), türkiye(3), tüyü(3), yemezler(3), yetimin(3), yönetemezler(3), adaletle(2), affetmeyeceğim(2), alamayız(2), aldıkları(2), almanya(2), avroyla(2), baronlarının(2), başladılar(2), beraber(2), bilirim(2), burnundan(2), destekleyeceğiz(2), değiştireceksin(2), diktatörler(2), dinleyecek(2), edeceğiz(2), elektrik(2), engel(2), etmenize(2), etmeyin(2), fakir(2), fransa(2), fukaranın(2), görmeyecek(2), hedefi(2), hesabını(2), hesap(2), hollanda(2), huzurunda(2), hırsızlık(2), isviçre(2), kaçak(2), koskoca(2), londra(2), mahkemeler(2), mücadele(2), olmasın(2), perişan(2), rüşvet(2), siyasette(2), son(2), sormaktır(2), soyuyorsanız(2), söylüyorum(2), söz(2), uyuşturucu(2)
   ctfidf: beşli(9; 9), alacağım(8; 8), götüreceksin(6; 6), kemal(6; 6), lazım(6; 6), çetelerden(5; 5), paraları(5; 5), devleti(5; 5)
   verbs:
c33 n=  28
   freq: ·milletin(32; 26), önüne(28; 28), türkiye(10; 10), seçim(9; 6), çıkar(9; 4), çıkıp(9; 9), açıklama(6; 2), diyecek(6; 3), düşünüyorsan(6; 2), erdoğan(6; 6), lazım(6), söylemek(6), israfa(5), yapacağım(5), yönetenler(5), çıkmak(5), devleti(4), fabrikasını(4), karşılayamaz(4), koalisyon(4), paraya(4), siyasi(4), son(4), söz(4), vermedik(4), yapmadılar(4), çıkacak(4), çıkıyor(4), anlatsa(3), açık(3), bakan(3), değerli(3), diyorsunuz(3), dünya(3), edebiyat(3), ediyorlar(3), getirdiniz(3), izin(3), karara(3), madde(3), oturursunuz(3), sarayda(3), sorun(3), vatandaş(3), yalan(3), önseçim(3), amerikalılara(2), anayasa(2), aydınlığa(2), bildirgelerine(2), buyurun(2), bütçe(2), büyüyor(2), cesareti(2), cumhuriyeti(2), değildir(2), değişikliği(2), diyemezsiniz(2), diğerine(2), dolar(2), dönemi(2), edeceksin(2), erken(2), gelecek(2), gelir(2), genel(2), gerekiyor(2), gittiler(2), hazırlar(2), hemen(2), herkese(2), hitler(2), hizmet(2), inanalım(2), irade(2), istanbullulara(2), kalkıp(2), kara(2), kardeşim(2), kesinlikle(2), konuştuğuna(2), kuralları(2), kılıçdaroğlu(2), mali(2), milletvekili(2), müdürü(2), paketi(2), palet(2), peşkeş(2), rüşvet(2), satıyorum(2), sağlaması(2), tank(2), tasarruf(2), telefon(2), teslim(2), vatansever(2), verdi(2), veriyorum(2), versin(2)
   ctfidf: önüne(28; 28), türkiye(10; 10), çıkıp(9; 9), seçim(6; 6), lazım(6; 6), erdoğan(6; 6)
   verbs:
c92 n=  35
   freq: para(108; 37), ·milletin(74; 42), harcadığınız(47; 27), belediye(28; 25), hesabını(28; 28), başkanı(27; 8), kuruşun(24; 18), vereceksiniz(22; 11), vermek(17; 9), yaptım(13; 6), söyledim(12), görev(9), ihaleleri(9), vatandaş(8), hesap(7), söylüyorum(7), yaparlar(7), yapıyoruz(7), halka(6), ödüyor(6), adalet(5), ayrım(5), devlet(5), hakkına(5), içinde(5), saygı(5), vergi(5), alacağım(4), arasında(4), beklenti(4), demektir(4), diyor(4), gerçekleştirirsin(4), hizmet(4), kardeşim(4), kul(4), kullandığınız(4), olacak(4), onurlu(4), veriyorlar(4), yapmayacaksınız(4), alıyorsunuz(3), andan(3), belde(3), dedim(3), ederiz(3), engel(3), facebook(3), gösterilecektir(3), güzel(3), harcıyorsan(3), hepsini(3), kimin(3), kimsenin(3), kucaklayacaksın(3), lazım(3), liraya(3), madde(3), seçildikten(3), siyaset(3), verdi(3), vermiyor(3), yatıracak(3), yeni(3), çalışılsın(3), çıkarıyorsunuz(3), ailelere(2), anlatmak(2), anlayış(2), arkadaş(2), bakın(2), biliyor(2), bütçen(2), canlı(2), cumhuriyet(2), demokrasiden(2), değerli(2), edemem(2), evet(2), eyvallah(2), eşit(2), gazilere(2), gelenekleri(2), gereğidir(2), götürdün(2), hepimizin(2), herkese(2), hukuk(2), istediğim(2), istiyorum(2), kabul(2), kaça(2), küçük(2), mansur(2), nedir(2), olun(2), parkı(2), parlamentoda(2), proje(2), sağ(2)
   ctfidf: para(92; 37), harcadığınız(33; 27), hesabını(28; 28), belediye(25; 25), kuruşun(18; 18), vereceksiniz(18; 11), vermek(9; 9), söyledim(9; 9), başkanı(8; 8), hesap(7), yaptım(6), söylüyorum(6), yaparlar(5), vergi(5), içinde(5)
   verbs:
c15 n=  66
   freq: mazlum(76; 76), ·milletlere(76; 40), cumhuriyet(60; 25), örnek(53; 53), ülke(52; 10), türkiye(43; 42), savaşı(37; 20), milli(29; 25), kurtuluş(28; 27), devlet(24; 9), demokrasi(23), dünyanın(20), mücadele(20), kurduktan(18), kemal(15), bağımsızlık(13), mustafa(12), verdikten(12), atatürk(11), olmuştur(11), partisi(11), gelişmiş(10), zamanda(10), büyük(9), gerçektir(8), olduk(8), yıl(8), değerli(7), olacak(7), emperyalist(6), gazi(6), inşa(6), kurulduktan(6), lazım(6), topraklarda(6), veren(6), çocuklarına(6), adaleti(5), değildir(5), geleceğim(5), getirmesini(5), halk(5), ilham(5), insan(5), meclisi(5), onlara(5), tarihi(5), çalıştık(5), aldığı(4), edeceğiz(4), ettiklerini(4), gençlerimiz(4), gerektiği(4), güçlere(4), hakları(4), kaldıracak(4), kuruluş(4), saygınlığı(4), taçlandıracağız(4), vardır(4), vermek(4), yöneten(4), önderlik(4), önemli(4), arkadaşları(3), asla(3), bağlamda(3), başlattığını(3), beraber(3), biliyordu(3), bilmeli(3), boyunca(3), bölgelerin(3), coğrafyada(3), devam(3), ediyorum(3), egemen(3), ezilen(3), filistin(3), geleneğinden(3), geliyoruz(3), güçlü(3), hepiniz(3), hukuk(3), islam(3), istiklal(3), istiyoruz(3), itibarı(3), işgal(3), kendimiz(3), kuvayı(3), laik(3), lideri(3), mağdur(3), milletvekilleri(3), müslüman(3), olduysa(3), olma(3), sonraki(3), sorunları(3)
   ctfidf: mazlum(76; 76), cumhuriyet(54; 25), örnek(53; 53), türkiye(42; 42), savaşı(32; 20), ülke(27; 10), kurtuluş(27; 27), milli(25; 25), devlet(18; 9), kemal(15), dünyanın(12), mustafa(12), demokrasi(11), atatürk(11), büyük(9), olmuştur(8), olduk(8), yıl(8), mücadele(7), değerli(7), kurduktan(6), bağımsızlık(6), inşa(6), zamanda(6), veren(6), gazi(6), lazım(6), ilham(5), değildir(5)
   verbs:
c78 n=  28

In [4]:
millet.subcluster(22, min_cluster_size=15, min_samples=5)
millet.subcluster(76, min_cluster_size=15, min_samples=5)
millet.subcluster(97, min_cluster_size=15, min_samples=5)
millet.subcluster(56, min_cluster_size=15, min_samples=5)
millet.subcluster(118, min_cluster_size=15, min_samples=5)
millet.subcluster(46, min_cluster_size=15, min_samples=5)

c22: 154 occurrence alt-kumeleniyor
  -> 4 alt-kume, noise 1%

  alt-kume 0 (n=50, faz={1: 7, 2: 17, 3: 26}) f1=0.8 f2=1.4 f3=0.9 [f2 1.4]
     freq: efendisidir(73; 47), köylü(55; 39), çiftçi(30; 9), cumhurbaşkanı(27; 22), diyen(26; 23), ananı(18; 18), kemal(17; 17), mustafa(16; 16), ülkeyi(14; 6), gazi(13; 13), atatürk(10), diyordu(9), yapacağız(8), çalışan(8), üreten(8), getirildi(7), kuran(7), sizlersiniz(7), söz(7), alın(6), demişti(6), döken(6), olacak(6), tarım(6), teri(6), zarar(6), üretici(6), birinci(5), bugündür(5), esnaf(5), gerçekten(5), lazım(5), lira(5), mersin(5), perişan(5), ürettiği(5), başkanı(4), cumhuriyetin(4), demek(4), diyecek(4), düşünün(4), emekli(4), fiyatları(4), haklarını(4), hepinize(4), iktidar(4), kazanacak(4), sonuncusu(4), baş(3), başladı(3), ediyorsunuz(3), etmediği(3), etmeye(3), hale(3), insanları(3), karnı(3), para(3), sahip(3), saygı(3), size(3), tefeci(3), temel(3), üretmek(3), ürünü(3), adayımızı(2), ana(2), anlamda(2), asgari(2), attıra(2), avrupa(2), banka(2), başka(2), buradadır(2), bölünmelidir(2), büyüklüğünü(2), davranacağız(2), dedi(2), dediler(2), dediği(2), dersin(2), devleti(2), deyince(2), direği(2), doyuralım(2), durumda(2), dönem(2), dünya(2), ekrem(2), elinden(2), evet(2), evlerimizde(2), faizi(2), gereken(2), geçti(2), günü(2), günün(2), güvenin(2), hazır(2), icra(2), ifade(2)
     ctfidf: efendisidir(67; 47), köylü(47; 39), diyen(23; 23), cumhurbaşkanı(22; 22), çiftçi(21; 9), ananı(18; 18), kemal(17; 17), mustafa(16; 16), gazi(13; 13), ülkeyi(11; 6), atatürk(10), yapacağız(7), teri(6), alın(6), sizlersiniz(5), mersin(5), diyordu(5), perişan(5), lazım(5), olacak(5)
     verbs:

  alt-kume 2 (n=42, faz={1: 4, 2: 4, 3: 34}) f1=0.6 f2=0.4 f3=1.4 [f3 1.4]
     freq: efendisidir(50; 18), çiftçi(50; 20), cumhurbaşkanı(21; 19), diyen(18; 18), ananı(14; 14), birincisinin(10; 4), kemal(10; 10), mustafa(10; 10), olacak(10; 10), atatürk(9; 9), gazi(9), emekli(8), partisinden(7), kurucusu(6), köylü(6), ülkenin(6), kazanacağız(5), perişan(5), size(5), sonuncusu(5), başkanı(4), biliyor(4), dediği(4), değildir(4), diyordu(4), doyuracak(4), esnafın(4), geldik(4), hale(4), ittifakıyız(4), lira(4), para(4), toprağa(4), uğraşanlara(4), vereceğiz(4), yozgat(4), çalışıp(4), adayı(3), altında(3), belediyeler(3), bilseydi(3), borcunu(3), derdi(3), diyerek(3), düşeceğini(3), emeği(3), gençler(3), gerçekten(3), hayvancılıkla(3), iktidara(3), imamoğlu(3), kanun(3), kimsesi(3), kredi(3), lazım(3), maalesef(3), maaşa(3), mazot(3), memleketin(3), noktadan(3), sahip(3), selam(3), söz(3), terini(3), yapmıyorlar(3), yılda(3), önceliği(3), üretti(3), aldılar(2), alkışlıyorlar(2), almanlara(2), alın(2), ağzındaki(2), bayramı(2), birer(2), birilerinin(2), birisinin(2), bırakmadık(2), cumhuriyetin(2), damlatan(2), dayanışma(2), demeyecek(2), durumu(2), duyayım(2), düşük(2), dışarıdan(2), edilen(2), ekmeğini(2), ekrem(2), elinden(2), ezilen(2), faizli(2), fiyat(2), gelecek(2), gelene(2), geliyor(2), getiremeyen(2), giden(2), gidin(2), görünce(2)
     ctfidf: efendisidir(36; 18), çiftçi(36; 20), cumhurbaşkanı(19; 19), diyen(18; 18), ananı(14; 14), mustafa(10; 10), kemal(10; 10), olacak(10; 10), gazi(9; 9), atatürk(9; 9), perişan(5), size(5)
     verbs:

  alt-kume 3 (n=31, faz={2: 1, 3: 30}) f1=0.0 f2=0.1 f3=1.6 [f3 1.6]
     freq: efendisi(28; 22), çiftçinin(28; 6), dediği(20; 19), köylüler(20; 5), atatürk(18; 18), kemal(11; 11), mustafa(11; 11), cumhurbaşkanı(10; 6), gazi(10; 10), ananı(8; 8), ağır(8), yüzde(7), diyen(6), emekli(6), geliyor(6), iktidarını(6), liralık(6), istiyoruz(5), üreticisi(5), birinci(4), buğday(4), diyormuş(4), esnafın(4), ittifakı(4), korkar(4), söz(4), tarım(4), taşıyamıyor(4), adana(3), dedikleri(3), deyince(3), duyuyoruz(3), fındık(3), hak(3), hayvancılıkla(3), içindeler(3), kavuşsun(3), kaybettiklerini(3), memleketi(3), sesinizi(3), seslenmek(3), tane(3), tarihini(3), vardır(3), vergi(3), çay(3), özel(3), ülkenin(3), adına(2), altın(2), anlatır(2), anlayış(2), asgari(2), bakın(2), başkanlarına(2), bey(2), beyefendiye(2), borcunu(2), buluşma(2), bırakmayan(2), cumhuriyeti(2), dayandı(2), denen(2), desteklemenin(2), doyur(2), düşmüş(2), ettiler(2), evlatlarımızdan(2), firmanın(2), geldik(2), gelince(2), geçinemiyoruz(2), halka(2), hesap(2), hor(2), işsiz(2), kalır(2), kara(2), kardeşi(2), karnına(2), karınca(2), karşılığını(2), kayıtlı(2), konuşmasını(2), küfeyi(2), kılmak(2), mazot(2), milleti(2), narenciye(2), nihai(2), olacak(2), onlara(2), perişan(2), saruhanlı(2), siftah(2), silelim(2), sonuncusunun(2), sorunlu(2), tamamladıktan(2), tutuksuz(2)
     ctfidf: efendisi(28; 22), dediği(19; 19), atatürk(18; 18), çiftçinin(11; 6), mustafa(11; 11), kemal(11; 11), gazi(10; 10), ananı(8; 8), ağır(8; 8), yüzde(7; 7), geliyor(6), cumhurbaşkanı(6), köylüler(5)
     verbs:

  alt-kume 1 (n=29, faz={1: 1, 2: 3, 3: 25}) f1=0.2 f2=0.4 f3=1.4 [f3 1.4]
     freq: efendisi(25; 25), çiftçiyi(22; 8), emeklinin(15; 4), köylüyü(13; 5), dediği(7; 7), esnafın(7; 4), göstereceğiz(7; 5), yapacağız(7; 7), ananı(6; 6), asgari(6; 6), sıkıntısı(6), çalışacağız(6), ücret(6), atatürk(5), düzende(5), gündemden(5), mücadele(5), bitireceğiz(4), konuşarak(4), mart(4), adaleti(3), arasındadır(3), beraber(3), birinin(3), bursa(3), cumhurbaşkanı(3), diyelim(3), dostu(3), doğrudur(3), dışarıdaki(3), ediyoruz(3), emekçinin(3), getirecek(3), geçim(3), güç(3), hakkını(3), hükümete(3), iktidar(3), kimdir(3), olacak(3), olduğumuz(3), para(3), sandığa(3), seçim(3), söz(3), taşıyacağız(3), yapar(3), yeni(3), yüzünü(3), üreticisinin(3), alacağız(2), artsın(2), asla(2), ağır(2), bitmez(2), budur(2), bırak(2), cebini(2), dedik(2), demokrasi(2), derdi(2), destek(2), değeri(2), diyordu(2), doldurmak(2), dönüşümü(2), elinde(2), emaneti(2), fiyatları(2), fındık(2), garibandan(2), gazi(2), görevimiz(2), görülen(2), götürülüyorsa(2), güldürmek(2), hedefimiz(2), ifadesini(2), istiyor(2), içeride(2), içindeki(2), işçi(2), kara(2), kardeşime(2), kemikte(2), kullandı(2), küfeyi(2), küfrü(2), maaşı(2), merhaba(2), millettir(2), milli(2), nedir(2), olmayacak(2), programlarını(2), sahiplerinin(2), seven(2), sopayla(2), tarlasında(2), tarım(2)
     ctfidf: efendisi(25; 25), çiftçiyi(13; 8), dediği(7; 7), yapacağız(7; 7), ananı(6; 6), asgari(6; 6), köylüyü(5; 5), göstereceğiz(5; 5), atatürk(5; 5)
     verbs:

c76: 130 occurrence alt-kumeleniyor
  -> 2 alt-kume, noise 0%

  alt-kume 1 (n=81, faz={1: 25, 2: 21, 3: 35}) f1=1.9 f2=1.1 f3=0.7 [f1 1.9]
     freq: milleti(27; 15), verdi(13; 5), başkan(12; 4), dedi(12; 12), veriyorlar(12; 6), yaptın(12; 4), çıkaracağım(12; 4), getirdiler(10; 2), anlatmıyorsunuz(9; 3), hakkı(9; 3), söyleyeyim(9), söylüyorum(9), iktidar(8), bakın(7), biliyor(7), gözünü(7), güvenerek(7), hesabını(7), konuş(7), kurum(7), lira(7), terör(7), vermek(7), yüzde(7), arkadaşlar(6), bitirdin(6), bırakmayacağız(6), dedik(6), diyorlar(6), harcadıkları(6), insanlar(6), istiyorlar(6), kardeşim(6), kullandı(6), olacak(6), paraları(6), vereceksiniz(6), ülke(6), allah(5), bakalım(5), başka(5), belediyeciliği(5), eder(5), gelir(5), gerçek(5), gösterdi(5), hesap(5), ifade(5), kapat(5), milletvekili(5), seçimde(5), söz(5), vatandaşlık(5), vergi(5), vermiyor(5), yönetim(5), çıkacak(5), anahtarıdır(4), asla(4), başına(4), beraber(4), cumhurbaşkanı(4), devleti(4), dolar(4), doğruları(4), filistin(4), fitil(4), geldi(4), gelin(4), gördü(4), güzel(4), halka(4), hatırlamakta(4), ikinci(4), kendileri(4), kibirli(4), lazım(4), mart(4), partili(4), perişan(4), sanıyor(4), soralım(4), süreci(4), tarafsız(4), uyuşturucu(4), yanlış(4), yapacağız(4), yapmadıklarını(4), yeni(4), yetmesin(4), zammı(4), çalışmıyor(4), çocuk(4), çıktı(4), alacağım(3), anayasa(3), ankara(3), anlayabilen(3), arkadan(3), barış(3)
     ctfidf: milleti(15; 15), dedi(12; 12), yüzde(7; 7), gözünü(6; 6), veriyorlar(6; 6), hesabını(6; 6), kardeşim(6; 6), söylüyorum(6; 6), eder(5; 5), bakalım(5; 5), verdi(5), arkadaşlar(5), allah(5), bakın(5), başka(5)
     verbs:

  alt-kume 0 (n=49, faz={1: 3, 2: 6, 3: 40}) f1=0.4 f2=0.5 f3=1.4 [f3 1.4]
     freq: görsün(10; 10), yayın(10; 2), demokrasi(9; 5), söyleyeyim(9; 3), gerçek(7; 3), getirecek(7; 3), kavga(7; 4), başkan(6; 4), iftirayı(6; 3), iktidarı(6; 3), meydan(6), partili(6), sistemi(6), ülke(6), adalet(5), arkadaşlar(5), darbe(5), falan(5), gelince(5), milletimiz(5), muhalefet(5), olacak(5), sandığı(5), seçim(5), siyaset(5), yapacağım(5), çıkar(5), bakalım(4), başına(4), beraber(4), bıktı(4), bırakmam(4), cevabını(4), duysun(4), ediyorduk(4), emeklinin(4), geldi(4), gelsin(4), gençler(4), güveniyorsanız(4), hesap(4), hodri(4), hukuk(4), istiyor(4), karşıma(4), savcı(4), söylüyorlar(4), topluyor(4), trt(4), verildiği(4), adam(3), atıyorlar(3), bakar(3), başladı(3), bekliyor(3), bilgi(3), bölgede(3), delirdi(3), diyecek(3), diyen(3), diyordun(3), doğruları(3), evet(3), gelirin(3), gelmiştir(3), giderse(3), gidiyorlar(3), görüyor(3), insana(3), istemiyor(3), istifa(3), isyan(3), karışlayacak(3), korku(3), saldırı(3), tane(3), türlü(3), varsa(3), vereceğim(3), vermesini(3), yapanları(3), adama(2), adamları(2), ahlak(2), aileleriyle(2), akşam(2), alnınızı(2), alın(2), anket(2), ateş(2), bakmam(2), bakıyor(2), boğanın(2), boş(2), bunlarda(2), canlı(2), canımız(2), cesaret(2), cevap(2), cumhurbaşkanına(2)
     ctfidf: görsün(10; 10), falan(5; 5), sandığı(5; 5), demokrasi(5; 5)
     verbs:

c97: 99 occurrence alt-kumeleniyor
  -> 2 alt-kume, noise 0%

  alt-kume 1 (n=55, faz={1: 11, 2: 8, 3: 36}) f1=1.2 f2=0.6 f3=1.1 [f1 1.2]
     freq: devletin(37; 13), vatanına(26; 8), milletine(23; 14), ülkeye(12; 5), bahseder(11; 11), bayrağına(10; 3), bağlı(10; 7), demokrat(9; 3), ittifakı(9; 7), partinin(9; 2), sahip(9), çıkaracağım(9), atatürk(8), hizmet(8), gözünü(7), insanları(7), sevginin(7), yapan(7), çalışanlara(7), bütünlüğüne(6), dediğiniz(6), değildir(6), ediyorum(6), etmek(6), konuşmalar(6), sadakati(6), saygı(6), askerin(5), başkan(5), cumhuriyeti(5), deprem(5), düşman(5), gençlerin(5), görev(5), kemal(5), milletvekilimiz(5), para(5), çıkmak(5), üstünde(5), adalet(4), anlatamaz(4), bölünmez(4), darbe(4), demokrasiyi(4), evet(4), gazi(4), gerekenler(4), günleri(4), güzel(4), hakkı(4), iktidara(4), isteriz(4), kabul(4), karşımızda(4), kimselerin(4), korksun(4), milliyetçi(4), mustafa(4), peşinde(4), siyasetçi(4), vardır(4), yaptık(4), çıkan(4), anlayışla(3), arkadaşımız(3), başkalarına(3), birinin(3), dedik(3), esnaf(3), eti(3), etmiyor(3), gerçek(3), geçen(3), gördük(3), göstereceğiz(3), huzur(3), içinde(3), işin(3), kadınların(3), kamu(3), konya(3), kullanacak(3), kurum(3), olacak(3), olanların(3), olmasını(3), söylüyorum(3), sıradan(3), tehdit(3), telefonuna(3), yapmadık(3), yardım(3), yerde(3), yolla(3), adım(2), akp(2), alacağım(2), allah(2), altındakilere(2), alıyorlardı(2)
     ctfidf: devletin(22; 13), milletine(14; 14), vatanına(13; 8), bahseder(11; 11), sahip(9; 9), bağlı(7; 7), ittifakı(7; 7), atatürk(7; 7), gözünü(6; 6), yapan(6; 6), hizmet(6), etmek(6), ülkeye(5), cumhuriyeti(5)
     verbs:

  alt-kume 0 (n=44, faz={1: 12, 2: 7, 3: 25}) f1=1.6 f2=0.7 f3=0.9 [f1 1.6]
     freq: milleti(41; 35), temsil(27; 26), devleti(15; 8), iktidar(12; 8), partinin(10; 3), korumak(8; 4), meclis(8; 4), milletvekili(8; 5), cumhurbaşkanı(7; 5), düşünen(6; 2), saygı(6), çalışana(6), ülke(6), anayasa(5), derdin(5), içinde(5), seçimle(5), yönetilemez(5), camiyi(4), değildir(4), değişiklikleri(4), ediyorlar(4), görüntü(4), hakimiyet(4), hakkını(4), hepimizi(4), karşımızdaki(4), komisyonun(4), makamı(4), milyonu(4), olmayacak(4), parlamento(4), rüşveti(4), seviyor(4), tarafsız(4), vardır(4), vatandaş(4), yapmasın(4), adamı(3), ahır(3), anlayana(3), bayrağı(3), başka(3), belediyelerin(3), beraber(3), cemaat(3), cepheye(3), darbeye(3), dedi(3), diyorlar(3), edemezler(3), eleştiriyorsunuz(3), etsin(3), geliyor(3), görevini(3), görüşün(3), hayır(3), karar(3), konuşmak(3), köyde(3), lazım(3), lira(3), mahkeme(3), mesela(3), milli(3), olsaydı(3), rahmetli(3), silkeleyin(3), söylüyorum(3), vatanı(3), yargı(3), yoktur(3), çıkar(3), akşam(2), anlamaya(2), anlatacaksın(2), asgari(2), asla(2), açık(2), bahçeli(2), barındırılan(2), başbakanken(2), başkan(2), başsağlığı(2), başına(2), bütçe(2), camide(2), camileri(2), cephaneler(2), cunta(2), demokrasi(2), devre(2), diliyor(2), duruşu(2), duymaktır(2), dönen(2), düşen(2), düşerseniz(2), ecevit(2), etmedik(2)
     ctfidf: milleti(35; 35), temsil(26; 26), devleti(13; 8), iktidar(8; 8), milletvekili(5; 5), anayasa(5; 5), cumhurbaşkanı(5; 5)
     verbs:

c56: 142 occurrence alt-kumeleniyor
  -> 2 alt-kume, noise 0%

  alt-kume 1 (n=112, faz={1: 6, 2: 2, 3: 104}) f1=0.3 f2=0.1 f3=1.6 [f3 1.6]
     freq: devletin(154; 52), kazanır(132; 48), karşıya(79; 39), yarışırsa(66; 17), milletle(52; 15), ajansı(35; 18), mart(34; 34), tarafında(31; 7), seçim(30; 7), partinin(20; 11), anadolu(18), demokrasi(18), verir(18), yanında(18), başkanı(17), gelirse(16), ittifakı(16), kullandı(16), getirildi(15), sever(15), vergi(15), değiştirir(14), evren(14), kenan(14), geldi(13), askere(12), söyleyeyim(12), tarihimiz(12), trt(12), dediği(11), seçti(11), özal(11), kaybetti(10), adayı(9), gider(9), ifade(9), verdiler(9), özel(9), almış(8), geçirenler(8), kaymakamları(8), kurduğu(8), saygılı(8), temmuz(8), yeni(8), ülkede(8), adayları(7), aklı(7), arkasında(7), atatürk(7), darbe(7), geçmiş(7), ilçe(7), insanlar(7), yayınlatmayan(7), yetkisini(7), yönetim(7), yüzden(7), çağırır(7), boyunca(6), dikilirse(6), dönüş(6), ele(6), ettiğinde(6), haber(6), karar(6), kendisidir(6), kusur(6), muhalefetin(6), sürecini(6), tayyip(6), televizyonunu(6), valileri(6), yanlış(6), çalıştı(6), akp(5), arasına(5), belediyelerin(5), cumhur(5), dikerseniz(5), emrine(5), gerekirse(5), günü(5), işaret(5), kurar(5), kurum(5), lazım(5), meclis(5), milletvekili(5), reklamını(5), sonuçlarına(5), sorun(5), vekili(5), yer(5), çeviren(5), alet(4), anayasa(4), başka(4), bence(4), biliyor(4)
     ctfidf: devletin(140; 52), kazanır(107; 48), karşıya(72; 39), milletle(46; 15), yarışırsa(39; 17), mart(34; 34), ajansı(30; 18), tarafında(19; 7), anadolu(18; 18), başkanı(16; 16), vergi(15), kenan(14), evren(14), verir(14), gelirse(13), sever(12), trt(12), seçim(12), özal(11), partinin(11), yanında(10), ittifakı(10), gider(9), geldi(9), özel(9), askere(8), almış(8), temmuz(8), yeni(8), ilçe(7), aklı(7), yüzden(7), demokrasi(7), atatürk(7), tarihimiz(6), ettiğinde(6), kurduğu(6), haber(6), ele(6), adayı(6), boyunca(6), tayyip(6), emrine(5), kurar(5), çağırır(5), işaret(5), cumhur(5), kullandı(5), akp(5), yer(5), günü(5)
     verbs:

  alt-kume 0 (n=30, faz={3: 30}) f1=0.0 f2=0.0 f3=1.7 [f3 1.7]
     freq: devleti(48; 28), karşısına(33; 28), kazandı(17; 6), verir(15; 14), askere(10; 4), dikersen(9; 5), kenan(9; 9), vergi(9; 6), evren(8; 8), gider(8; 6), dedi(7), seçim(7), özal(7), darbe(6), diktiler(6), milleti(6), sandığı(6), seçti(6), yönetmeye(6), canını(5), dediğinde(5), dikilirse(5), gerekirse(5), iktidarın(5), irade(5), mart(5), sever(5), seçeceksin(5), temmuz(5), ajansı(4), anadolu(4), gelir(4), istenir(4), verdi(4), örnek(4), değiştirir(3), direnir(3), gerçek(3), girişiminde(3), haberler(3), istediler(3), kalktığında(3), kullanan(3), partinin(3), sahip(3), söylediğim(3), vermez(3), çağırır(3), şehit(3), adayı(2), anayasasını(2), arkadaşlarına(2), atatürk(2), ayrı(2), başkanı(2), başına(2), bugüne(2), cumhuriyeti(2), dedik(2), der(2), dersin(2), dikiyorlar(2), evladına(2), geldi(2), geleceğine(2), geliyor(2), geçen(2), gitti(2), görüntü(2), gösterecek(2), gücünü(2), hatayı(2), hoşlanmaz(2), ilan(2), istikamet(2), kendine(2), kişinin(2), kökenliyi(2), mücadele(2), olmadık(2), ortak(2), oylarda(2), parlamento(2), paşayı(2), rektör(2), sağ(2), sorumludur(2), tarafta(2), tarih(2), trt(2), tutsak(2), vardır(2), versin(2), yapar(2), yaptıklarından(2), yapılacak(2), yarışır(2), yerde(2), yere(2), çıkar(2)
     ctfidf: devleti(42; 28), karşısına(28; 28), verir(14; 14), kazandı(12; 6), kenan(9; 9), evren(8; 8), özal(7; 7), dedi(7; 7), gider(6; 6), vergi(6; 6), dikersen(5), sever(5), canını(5), gerekirse(5), temmuz(5), mart(5)
     verbs:

c118: 240 occurrence alt-kumeleniyor
  -> 7 alt-kume, noise 24%

  alt-kume 2 (n=56, faz={1: 1, 2: 6, 3: 49}) f1=0.1 f2=0.5 f3=1.5 [f3 1.5]
     freq: verdi(18; 15), milletimiz(15; 10), sandık(15; 4), seçimde(15; 4), gösterecek(13; 8), kredi(13; 7), başkan(11; 5), konuşulacak(10; 5), yetkiyi(10; 6), mart(9; 8), yöneteceğiz(9), anayasanın(8), cumhurbaşkanlığı(8), size(8), anlamadılar(7), demokrasi(7), emekliyi(7), onlara(7), çalışmaktadır(7), darbe(6), değildir(6), iktidar(6), partiler(6), vermedi(6), birinci(5), geldiğinde(5), görevi(5), hükmünü(5), istiyorum(5), koyuyorsun(5), mağduriyetine(5), saymaya(5), sorumluluğu(5), tüketici(5), adayı(4), asgari(4), bırakın(4), cezaevine(4), dersini(4), devleti(4), diyorum(4), düzeni(4), gider(4), halktan(4), içine(4), kasım(4), kurulmuş(4), küfe(4), küfenin(4), saygıyı(4), tanımazlık(4), verecek(4), yalova(4), yargıtay(4), yıl(4), ücret(4), üstünde(4), adana(3), aldığı(3), anlatan(3), arkadaş(3), açtı(3), bayram(3), bağlarsan(3), başlayacağı(3), bekledi(3), biliyor(3), bizimle(3), dedi(3), dedik(3), demek(3), ekrem(3), geliyor(3), görmek(3), görürse(3), günü(3), güzel(3), harca(3), hatırlatsın(3), hazırladık(3), hepinizden(3), istanbul(3), istemiyor(3), kartı(3), kazanamadıkları(3), layık(3), olacak(3), sarı(3), silivri(3), sorun(3), tayyip(3), tokadını(3), vermiş(3), yapılanlarda(3), yattı(3), yeri(3), yüzden(3), çıkardığında(3), çıktı(3), özel(3)
     ctfidf: verdi(15; 15), kredi(12; 7), milletimiz(10; 10), gösterecek(8; 8), mart(8; 8), size(8; 8), onlara(7; 7), yetkiyi(6; 6), konuşulacak(5; 5), tüketici(5; 5), birinci(5), demokrasi(5), başkan(5)
     verbs:

  alt-kume 5 (n=36, faz={1: 2, 2: 4, 3: 30}) f1=0.3 f2=0.5 f3=1.4 [f3 1.4]
     freq: biliyor(7; 6), darbesi(6; 2), görüyor(6; 6), milletimiz(6; 6), demektir(5; 3), gördü(5; 3), hizmet(5; 4), kazandı(5; 2), bulundu(4; 1), görmeyecek(4; 2), görür(4), maaş(4), meclis(4), unutmasın(4), veriyoruz(4), vermek(4), yüzde(4), üstünde(4), adaletsizlik(3), anda(3), belediyeciliktir(3), bunlara(3), cumhurbaşkanı(3), dem(3), diyecek(3), emekliye(3), getirdi(3), görmüyor(3), insanlar(3), karşılamadı(3), katkısını(3), kavga(3), kullandı(3), kötü(3), mansur(3), sandıkla(3), sanmasın(3), sindirememektedir(3), yaptıklarından(3), yavaş(3), yemezler(3), yolsuzluk(3), zam(3), çıktı(3), ülkede(3), adaylardan(2), allah(2), anlaşma(2), ayağa(2), ayrı(2), bakın(2), baş(2), başarısız(2), bire(2), birinci(2), bıktık(2), cayır(2), cümle(2), dedi(2), denen(2), destek(2), diyormuş(2), duracaksınız(2), düşürdüler(2), ekrem(2), esası(2), etmiş(2), gençlerin(2), gerçekleşme(2), geçen(2), gönül(2), göstermedi(2), gözü(2), günden(2), hazımsızlık(2), hükümet(2), iddianame(2), iftira(2), indiren(2), israil(2), istanbul(2), istediler(2), içine(2), kabul(2), kaldı(2), kalktı(2), kardeşim(2), kemal(2), kimseye(2), konusu(2), konuşmadı(2), kumpas(2), kurultay(2), kuruş(2), kılıç(2), lazım(2), lira(2), maalesef(2), mustafa(2), netanyahu(2)
     ctfidf: görüyor(6; 6), biliyor(6; 6), milletimiz(6; 6)
     verbs:

  alt-kume 6 (n=26, faz={1: 1, 3: 25}) f1=0.2 f2=0.0 f3=1.6 [f3 1.6]

## Merging Clusters into Groups

In [3]:
millet.kwic_in_cluster(cluster=39, context_words=["polis"])
#millet.kwic_in_cluster(cluster=85)
# millet.kwic_in_cluster(cluster=56) artefakt
# millet.kwic_in_cluster(cluster=23)
#millet.kwic_in_cluster(cluster=28, context_words=["aziz"])
# millet.kwic_in_cluster(cluster=4)
# millet.kwic_in_cluster(cluster=54)
#millet.kwic_in_cluster(cluster=114)
#millet.kwic_in_cluster(cluster=106)
#millet.kwic_in_cluster(cluster=41, context_words=["kalesi"]) # müthiş bir küme 
#millet.kwic_in_cluster(cluster=41, phase="f1") # mekansal bağlam yakalamış
#millet.kwic_in_cluster(cluster=74, context_words=["çıkar, devlet"])
#millet.kwic_in_cluster(cluster=73)
# millet.kwic_in_cluster(cluster=116) # pure national will güzel incelenir kayma da var "millet diyor ki"
# millet.kwic_in_cluster(cluster=117, context_words=["artık"])
#millet.kwic_in_cluster(cluster=50, context_words=["türk"])
#millet.kwic_in_cluster(cluster=121, context_words=["perişan"])

'millet' (c39): 6 occurrence

,doc_id,date,phase,venue,match
3348,parliament_kilicdaroglu_10042018_244,2018-04-10,1,parliament,"vatandaş millet öder ve polis maaşını alır. O nedenle polis hükümetin değil, polis devletin ve milletin polisidir. O nedenle söylüyorum, polise sıkılan her kurşun millete sıkılmış kurşundur. Polisimizi korumak zorundayız. Üçüncü soru: Polis devletin değil de, hükümetin polisi olursa ne"
7419,event_kilicdaroglu_02112017_848,2017-11-02,1,event,"Genel Başkanı Kemal Kılıçdaroğlu: - Polise, askere sıkılan her kurşun, millete sıkılmış kurşundur. Kurşunlara karşı bu ülkenin birliği ve bütünlüğü için hepimiz gerektiğinde göğsümüzü gereceğiz ve"
7422,event_kilicdaroglu_02112017_848,2017-11-02,1,event,"insanlık suçudur. Hep birlikte teröre karşı ortak bir duruş sergilemeliyiz. Polise, askere sıkılan her kurşun, millete sıkılmış kurşundur. Kurşunlara karşı bu ülkenin birliği ve bütünlüğü için hepimiz gerektiğinde göğsümüzü gereceğiz ve"
7435,event_kilicdaroglu_07062017_867,2017-06-07,1,event,"şunu söyledim, burada da söyleyeyim. Yani Burdur’da da söyleyeyim. Polisimize veya askerimize sıkılan her kurşun milletimize sıkılmış kurşundur. Dolayısıyla polisimizin ve askerimizin güvenliği çok önemlidir. Çünkü onlar bizim güvenliğimiz için, bizim"
7603,event_kilicdaroglu_10042017_885,2017-04-10,1,event,"için, hepimizin huzuru için. O nedenle hep söyledim yine de söylüyorum, polise sıkılan her kurşun millete sıkılmış bir kurşundur. Askere sıkılan her kurşun millete sıkılmış bir kurşundur. Biz ayrım yapmıyoruz. Polis arkadaşlardan her gittiğim yerde şunu istedim, milletin polisi"
1460,parliament_kilicdaroglu_17012017_288,2017-01-17,1,parliament,"yaptıklarını biliyoruz, günün yirmi dört saati çalışıyorlar. Söyledim, yine söyleyeceğim, polise, askere sıkılan her kurşun millete sıkılmış demektir, asla kabul etmiyoruz, asla. Terörü her yerde ve her ortamda lanetledik, yine lanetliyoruz."

In [3]:
# 5, 6 56, editorial artefakt; 34, 33: baş sağlığı; 102: kıbrıs düşük frekans, 23: sözüm var, 63: yapamadım; 118 yapamadım; 73 anayasa; 56: artefakt
# 61 35 yapamadım

millet.set_cluster_group("Accountability Node", [22, 110, 109, 94, 88, 103, 91, 92, 18]) 
millet.set_cluster_group("Demands & Problems Node", [7, 95, 47, 93, 52, 123, 57, 112, 119])
millet.set_cluster_group("Antagonist: Erdoğan", [81, 96, 97, 90, 99, 48, 86, 32, 80, 107, 38, 87, 54, 124, 19, 117, 121, 111,64, 68]) # 70 çok unique oraya dal
millet.set_cluster_group("Nation's Will", [104, 105, 115, 113, 16, 58, 9, 42, 116, 89, 75,31, 127, 126, 20]) #73, 116 anlamlı
millet.set_cluster_group("Nationalism", [12, 13, 59, 51, 0, 53, 10])
millet.set_cluster_group("Foundation Node", [29, 45, 44, 71])
millet.set_cluster_group("Peasant as the Master", [24, 25, 26])
#millet.set_cluster_group("TBMM", [1, 82, 27])
millet.set_cluster_group("Democracy", [83, 85, 21, 106, 43])
millet.set_cluster_group("State Node", [70, 39,108, 74, 84, 76]) 
millet.set_cluster_group("Appeal to the Nation", [101, 65, 46, 55, 14, 40, 17, 28, 30])
millet.set_cluster_group("Resistance Rhetoric & Imamoğlu", [8, 72, 49, 69, 4, 114, 125, 11, 62, 122, 120]) 
millet.set_cluster_group("Sovereignty Node", [41, 50, 15, 67, 66]) # 41 kurumsal -> coğrafi duygusal kayış bulgusu
millet.set_cluster_group("Nation Alliance", [3])
#millet.set_cluster_group("UN", [2])
millet.set_cluster_group("Service Node", [78, 60, 77])

In [3]:
millet.set_cluster_group("Hesap Vermek", [22, 110, 109, 94, 88, 103, 91, 92, 18]) 
millet.set_cluster_group("Talepleri ve Problemler", [7, 95, 47, 93, 52, 123, 57, 112, 119])
millet.set_cluster_group("Erdoğan", [81, 55, 14, 96, 101, 97, 90, 99, 48, 86, 32, 80, 107, 38, 87, 54, 124, 19, 117, 121, 111,64, 68]) # 70 çok unique oraya dal
millet.set_cluster_group("Milli İrade", [104, 105, 115, 113, 16, 58, 9, 42, 116, 89, 75,31, 127, 126, 20]) #73, 116 anlamlı
millet.set_cluster_group("Milliyetçilik", [12, 13, 59, 51, 0, 53, 10])
millet.set_cluster_group("Kurucu İktidar", [29, 45, 44, 71])
millet.set_cluster_group("Köylü Milletin Efendisidir", [24, 25, 26])
#millet.set_cluster_group("TBMM", [1, 82, 27])
millet.set_cluster_group("Demokrasi", [83, 85, 21, 106, 43])
millet.set_cluster_group("Devlet", [70, 39,108, 74, 84, 76, 65]) 
millet.set_cluster_group("Direniş Retoriği & İmamoğlu", [8, 72, 49, 69, 4, 114, 125, 11, 62, 122, 120]) 
millet.set_cluster_group("Egemenlik", [41, 50, 15, 67, 66]) # 41 kurumsal -> coğrafi duygusal kayış bulgusu
#millet.set_cluster_group("Millet İttifakı", [3])
#millet.set_cluster_group("UN", [2])
millet.set_cluster_group("Hizmet", [78, 60, 77]) 
millet.set_cluster_group("Para ve Varlık", [46])

# 55 milletim beni affetsin

In [5]:
# millet.group_members("Antagonist: Corruption", words="ctfidf", top=30 )
# millet.print_group("Antagonist: Corruption")
# millet.group_members("Demand & Struggle Node", words="ctfidf", top=30)
#millet.print_group("Demands & Problems Node")
#millet.group_members("Antagonist: Erdoğan", words="freq", top=200)
#millet.print_group("Antagonist: Erdoğan") # 18, 81, 21, 83, 70, 38
# millet.kwic_in_cluster(cluster=18, context_words=["önüne"]) -> acc.
# millet.kwic_in_cluster(cluster=81)
# millet.kwic_in_cluster(cluster=21)
# millet.kwic_in_cluster(cluster=21)
# millet.kwic_in_cluster(cluster=83) 
# millet.kwic_in_cluster(cluster=70, context_words=["devlet"])
# millet.group_members("Imamoğlu?", words="ctfidf", top=30) -> looks meaningful for special Imamoğlu node though it has low freq
# millet.group_members("Turkiye Node,", words="ctfidf", top=30)
# millet.group_members("Resistance Rhetoric", words="ctfidf", top=30)
#millet.group_members("Antagonist: Intangible", words="ctfidf", top=30)
#millet.print_group("Antagonist: Intangible")
# millet.kwic_in_cluster(cluster=118, context_words=["lira"])
#

In [4]:
millet.plot_phase_heatmap(save_dir="figures", show=False, fmt="pdf")

saved: figures/millet_phase_heatmap.pdf
saved: C:\Users\user\Desktop\Thesis\latex\figures/millet_phase_heatmap.pdf

In [7]:
# HDBSCAN'in kumeledigi (noise haric)
total_clustered = (millet.m.cluster != -1).sum()

# meta-gruplara atanan
assigned = set()
for name in millet.cluster_groups:
    assigned |= set(millet.cluster_groups[name])
in_meta = millet.m.cluster.isin(assigned).sum()

print("HDBSCAN kumeledi:", total_clustered)
print("meta-gruba atandi:", in_meta)
print("meta disi (kume var ama gruba girmemis):", total_clustered - in_meta)

HDBSCAN kumeledi: 8473
meta-gruba atandi: 7628
meta disi (kume var ama gruba girmemis): 845

In [14]:
total = millet.m[millet.m["cluster"] != -1]["cluster"].nunique()
grouped_ids = {cid for ids in millet.cluster_groups.values() for cid in ids}
grouped = len(grouped_ids)
total_occ = (millet.m["cluster"] != -1).sum()
grouped_occ = millet.m["cluster"].isin(grouped_ids).sum()
pct = 100 * grouped_occ / total_occ
print(f"{millet.term}: {grouped}/{total} kume gruplandi ({total-grouped} disarida), "
      f"occurrence kapsama {pct:.0f}%")

millet: 111/128 kume gruplandi (17 disarida), occurrence kapsama 90%

In [9]:
#millet.kwic_in_cluster(cluster=35, context_words=["yüzde"])
# millet.kwic_in_cluster(cluster=55, context_words=["özür"]) -> müthiş zengin bir çıktı
# millet.kwic_in_cluster(cluster=62, phase="f3")
# millet.kwic_in_cluster(cluster=71)
#millet.kwic_in_cluster(cluster= 4)
# millet.kwic_in_cluster(cluster=54, context_words=["allah"])
# millet.kwic_in_cluster(cluster=76, context_words=["emekliler"])
# millet.kwic_in_cluster(cluster=84)
# millet.kwic_in_cluster(cluster=40, context_words=["seçim"])
#millet.kwic_in_cluster(cluster=51, context_words=["büyük"])
#millet.kwic_in_cluster(cluster=78, context_words=["hizmet"])
#millet.group_members("Appeal to the Nation", words="ctfidf", top=30)
#millet.print_group("Foundation")
#millet.print_group("Appeal to the Nation")
#millet.print_group("Demand & Problems Node")
#millet.print_group("Nationalism")
#millet.print_group("National Sovereignty")

In [10]:
#millet.print_group("Foundation Node")
#millet.kwic_in_cluster(cluster=45, context_words=["kongresi"])
#millet.print_group("Nationalism")
#millet.print_group("Antagonist: Erdoğan")
#millet.kwic_in_cluster(cluster=81, context_words=["kuyruğu"])
millet.kwic_in_cluster(cluster=97, context_words=["yakasından"])

'millet' (c97): 6 occurrence

,doc_id,date,phase,venue,match
5475,rally_ozel_21012026_21,2026-01-21,3,rally,"paçayı kurtarmaya çalışıyorsa, o çoktan bitmiştir. Erdoğan tükenmiştir. Buradan Erdoğan’a sesleniyorum. Bu bir tükenmişlik sendromudur. Millete yalan, iktidarın dönülmeyen son virajıdır. Savruldun, beceremiyorsun ve artık yalana sarıldın. Düş milletin yakasından. Getir sandığı. Millet senden zam değil, sandık bekliyor. ZAFERİ BİZ KAZANACAĞIZ Bu arada şurada"
2584,parliament_ozel_21102025_15,2025-10-21,3,parliament,"meydanlardayız, sokaklardayız, canlı yayındayız ya. Arkadaşlarımız masumdur. İftiracısınız. Yazıklar olsun sana, yazıklar olsun iftiralarına. Düş milletin yakasından. Düş milletin yakasından. Ya kanıtla, ya özür dile çek git. Al o beceriksizi oradan. Zulmetme artık. Dünkü"
6561,rally_ozel_26042024_167,2024-04-26,3,rally,"EŞİĞİNDE Çok sayıda şirket iflasın eşiğindedir. Konkordatonun eşiğindedir. İş bilmezler, size sesleniyoruz. Yeter artık, düşün milletin yakasından. Denizli’nin güzel insanları. 31 Mart seçimleri yeni bir siyasi hat çizmiştir. Bu siyasi hat"
7213,event_kilicdaroglu_06102018_737,2018-10-06,1,event,"Bu ülkeyi kim yönetiyor, sen mi yönetiyorsun, dış güçler mi yönetiyor? Dış güçler yönetiyorsa düş milletin yakasından kardeşim. Sen yönetiyorsan ülkeyi dış güçlere teslim etme kardeşim. Bu kadar açık, bu kadar"
3416,parliament_kilicdaroglu_02102018_235,2018-10-02,1,parliament,"Türkiye Cumhuriyeti'ni ve 16 bakanlığı bir Amerikan şirketine denetletiyorsanız sizin sarayda da yeriniz yoktur. Düşün milletin yakasından.. Genel Başkan Kılıçdaroğlu’nun TBMM CHP Grup Toplantısında yaptığı konuşma şöyle: Değerli arkadaşlarım, parlamentoda yeni"
3423,parliament_kilicdaroglu_02102018_235,2018-10-02,1,parliament,"Türkiye Cumhuriyeti ve 16 bakanlığı bir Amerikan şirketine denetletiyorsanız, sizin sarayda da yeriniz yoktur. Düşün milletin yakasından. Bu sözü niye söyledim? 6 Mart 1922, Türkiye Büyük Millet Meclisinde gizli bir toplantı yapılır. Gazi Mustafa Kemal kürsüye çıkar ve şöyle söyler: Hangi istiklâl"

In [12]:
print(millet.latex_group_table_short(
    picked=["Foundation Node", "Sovereignty Node", "Nationalism", "Antagonist: Erdoğan", "Nation's Will", "State Node", "Peasant as the Master", "Resistance Rhetoric & Imamoğlu"],  
    top_words=30,
    signifier="millet",
    reduce_frequent="shared",
    shared_penalty=0.4,
    keep=["erdoğan"]))

\begin{table}[H]
\centering
\footnotesize
\caption{Selected contextual clusters of \sig{millet} and their phase-specific lift. Terms are selected and ordered by c-TF-IDF score; parenthetical counts are raw frequencies (inflections merged).}
\label{tab:clusters-millet}
\vspace{0.5em}
\begin{tabular}{p{2.5cm} r r r p{8cm}}
\toprule
\textbf{Cluster (n)} & \textbf{KK-E} & \textbf{KK-L} & \textbf{Özel} & \textbf{Representative terms (freq.)} \\
\midrule
\raggedright \textbf{Foundation Node} (270)
  & \textbf{1.6} & 1.4 & 0.6
  & milletin (417), mazlum (77), istiklalini (52), azim (59), amasya (54), kurtuluş (42), tamimi (23), kaderini (27), kongresi (20), ülkenin (78), kararı (67), cumhuriyet (83), savaşı (52), eğitimdir (12), işgal (17), demokrasiyi (54), emperyalist (10), zafere (13), esaret (9), tarihi (38), milli (56), türkiye (66), çanakkale (14), egemen (13), bağımsız (34), örnek (54), mahkemesine (30), mücadele (37), topluluk (7), devlet (41) \\
\addlinespace
\raggedright \textbf{Sovereignty Node} (399)
  & \textbf{1.3} & 0.9 & 1.0
  & egemenlik (182), milletin (581), kalesidir (106), kayıtsız (103), şartsız (103), kaydü (46), şart (48), hakimiyet (35), anayasa (103), bila (33), temsilcileri (26), meclis (77), divanıdır (16), cumhuriyet (82), sofrasına (16), irade (67), mekanı (14), erdoğan (39), partisi (80), organları (15), evinde (16), ilkesinden (12), masası (11), türkiye (77), hakemliğine (36), devlet (59), türk (65), malını (14), padişahın (11), patron (12) \\
\addlinespace
\raggedright \textbf{Nationalism} (330)
  & 1.0 & 0.8 & \textbf{1.1}
  & sevgisi (95), milletinin (248), yüreğinde (59), vatan (170), bayrak (143), şerefim (36), renklerini (41), ittifakı (115), türkiye (149), yıldızlı (31), bütündür (19), türk (113), gücümle (16), atatürk (99), gücünü (28), ülkenin (52), insanları (60), parti (76), kalbinde (15), devleti (64), beyaz (26), demokratlar (43), kırmızı (23), büyük (71), halk (48), mektubu (14), cumhuriyeti (62), tarafsızlıkla (28), güzel (67), yürekli (10) \\
\addlinespace
\raggedright \textbf{Antagonist: Erdoğan} (1440)
  & 0.9 & 0.7 & \textbf{1.2}
  & milletin (1244), erdoğan (257), parti (268), vicdanına (128), yüzüne (48), başkan (166), aklıyla (32), savcı (39), yakasından (37), kuyruğu (28), yoksulluk (40), siyasi (136), iktidar (145), darbe (129), seçim (135), zam (37), fakir (30), karşısına (103), hakkını (113), devlet (142), çadır (29), alay (31), perişan (48), belediye (117), terör (37), türkiye (163), meydan (105), pazar (27), ülkenin (114), kayyum (26) \\
\addlinespace
\raggedright \textbf{Nation's Will} (922)
  & 0.6 & 0.9 & \textbf{1.2}
  & milletin (834), iradesine (253), seçim (271), partisi (289), ferasetine (58), erdoğan (102), halk (168), iktidar (148), kararı (112), başkanı (125), demokrasi (152), oylarıyla (33), adayımı (77), belediye (106), gücünü (31), darbe (103), cumhurbaşkanı (107), saygı (98), siyasi (93), türkiye (123), mesajını (21), yanımda (20), iddianame (19), oyuyla (18), sağduyusuna (23), sandığa (63), hak (58), cunta (17), tokadı (16), cumhuriyet (89) \\
\addlinespace
\raggedright \textbf{State Node} (350)
  & 0.6 & 0.4 & \textbf{1.5}
  & devlet (449), milletin (408), çıkarlarını (42), ajansı (40), karşısına (137), polis (35), evladı (63), kenan (24), kurşun (19), partisi (90), evren (23), özal (18), sever (18), erdoğan (35), tarafta (37), askere (39), anadolu (24), trt (15), kaymakamlarını (9), seçim (46), menfaati (10), bütünlüğü (10), başkanı (51), valileri (8), bağlı (12), türkiye (59), vatanına (27), yanındaydı (20), ülkenin (45), elleri (9) \\
\addlinespace
\raggedright \textbf{Peasant as the Master} (136)
  & 0.4 & 0.5 & \textbf{1.5}
  & efendisi (159), köylü (89), ananı (46), çiftçi (114), milletin (159), tarım (13), cumhurbaşkanı (55), emekli (29), fiyatları (7), hayvancılıkla (6), perişan (12), narenciye (5), atatürk (37), esnafın (18), kemal (36), yozgat (6), mustafa (35), fındık (6), işçi (6), partisi (21), gazi (31), sonuncusu (11), karnı (5), yazıklar (6), türkiye (26), emeği (4), ülkenin (20), cambaza (3), ürünler (3), lira (14) \\
\addlinespace
\raggedright \textbf{Resistance Rhetoric & Imamoğlu} (535)
  & 0.2 & 0.2 & \textbf{1.7}
  & milletin (581), gönlünde (122), partisi (234), santim (51), erdoğan (82), kelime (29), inatlaşılır (20), başkanı (88), gözünden (61), anketlerde (18), belediye (78), eksik (30), halk (89), karşısında (58), darbe (72), seçim (73), verene (20), adayı (53), girişimi (20), geriye (23), aday (25), iktidar (70), siyasi (62), ülkeyi (64), türkiye (76), görev (54), mücadele (43), cumhuriyet (63), işçi (12), butlan (8) \\
\addlinespace
\midrule
\raggedright \textit{Shared across clusters}
  & & &
  & türkiye (2339), meclisi (1812), partisi (1782), büyük (1546), devlet (1239), başkanı (1105), ittifakı (929), seçim (918), halk (877), siyasi (821), ülkenin (805), cumhuriyet (803), erdoğan (743), demokrasi (730), iktidar (710) \\
\bottomrule
\end{tabular}
\end{table}

In [13]:
print(millet.latex_group_table(top_words=30, reduce_frequent="shared", shared_penalty=0.4, keep=["erdoğan"]))

\footnotesize
\begin{longtable}{l r r r p{7cm}}
\caption{Contextual clusters of \textit{hak}...} \\
\toprule
\textbf{Cluster (n)} & \textbf{KK-E} & \textbf{KK-L} & \textbf{Özel} & \textbf{Representative terms (freq.)} \\
\midrule
\endfirsthead

\multicolumn{5}{c}{\tablename\ \thetable\ \textit{(devamı)}} \\
\toprule
\textbf{Cluster (n)} & \textbf{KK-E} & \textbf{KK-L} & \textbf{Özel} & \textbf{Representative terms (freq.)} \\
\midrule
\endhead

\bottomrule
\endlastfoot

\raggedright \textbf{UN} \newline (266)
  & \textbf{2.3} & 1.0 & 0.5
  & milletler (299), dilekçe (41), işkence (34), uluslararası (51), sözleşmesi (24), filistin (31), insanca (67), rapor (21), adil (36), konseyi (19), türkiye (116), suriyelilerin (14), güvenlik (19), dünya (78), sağlanacak (13), cezayir (12), ülke (56), suriye (23), kudüs (12), devlet (47), halit (10), temsilcisi (18), israil (18), hükümeti (38), devreye (8), ohal (12), iran (10), kararı (36), güvenliğinin (9), esad (8) \\[8pt]
\raggedright \textbf{TBMM} \newline (975)
  & \textbf{2.1} & 1.4 & 0.4
  & meclisi (1404), türkiye (1117), büyük (1082), vekili (129), komisyonu (88), sayıştay (76), başkanı (278), denetim (50), milletvekili (212), önergesi (39), bilgi (53), organı (46), temsil (69), partisi (214), bütçe (52), milletin (214), raporları (38), yetkisi (124), teklifi (38), başkomutanlık (24), kanun (109), bakanlığı (85), nisan (45), iradeyi (106), kurtuluş (46), parlamenter (100), grubu (27), girişimini (26), kongresi (21), arkadaşlarım (109) \\[8pt]
\raggedright \textbf{Foundation Node} \newline (270)
  & \textbf{1.6} & 1.4 & 0.6
  & milletin (417), mazlum (77), istiklalini (52), azim (59), amasya (54), kurtuluş (42), tamimi (23), kaderini (27), kongresi (20), ülkenin (78), kararı (67), cumhuriyet (83), savaşı (52), eğitimdir (12), işgal (17), demokrasiyi (54), emperyalist (10), zafere (13), esaret (9), tarihi (38), milli (56), türkiye (66), çanakkale (14), egemen (13), bağımsız (34), örnek (54), mahkemesine (30), mücadele (37), topluluk (7), devlet (41) \\[8pt]
\raggedright \textbf{Accountability Node} \newline (347)
  & 1.3 & \textbf{2.1} & 0.3
  & kuruşun (158), millete (418), para (213), cebinden (47), hesabını (180), doları (31), siyaset (94), verginin (57), yatırımın (13), başkanı (61), devleti (73), belediye (62), bay (21), hesap (69), halk (57), bütçe (15), belde (12), hortumları (9), köprüyü (11), hazineden (9), israf (12), anlayışı (35), erdoğan (24), kul (17), hakkı (40), şeffaflık (8), vakıf (8), kaynağı (8), vatandaştan (30), onurlu (29) \\[8pt]
\raggedright \textbf{Nation Alliance} \newline (445)
  & 0.9 & \textbf{2.6} & 0.2
  & ittifakı (650), parti (172), çoğunluğu (30), ilkelere (27), muharrem (30), başkanı (101), seçim (95), cumhur (42), ince (30), türkiye (130), demokrasi (95), iktidar (81), dostlarımızla (14), saadet (17), lider (45), metnimizin (11), cumhurbaşkanı (77), bileşenleri (12), söz (58), akşener (14), belediye (63), seçmen (13), ülkeye (56), aradayız (14), meral (12), şeklinde (12), parlamentoda (47), beraber (56), güvenliği (11), otoriter (11) \\[8pt]
\raggedright \textbf{Democracy} \newline (202)
  & \textbf{1.2} & 1.1 & 0.8
  & vekilini (56), milletin (272), listeyi (22), temsil (34), parti (74), milletvekili (61), refahını (13), huzurunu (37), erdoğan (27), çıkarları (12), barajı (11), görevi (35), seçim (45), vesayet (12), yasasının (7), muhtar (9), darbe (28), krizi (8), siyasi (35), rüşvet (7), birliğini (17), vazifeyi (7), ülkenin (31), devlet (32), başkanlar (21), zengin (7), koalisyonun (5), vatandaş (24), önüne (33), sultasının (5) \\[8pt]
\raggedright \textbf{Sovereignty Node} \newline (399)
  & \textbf{1.3} & 0.9 & 1.0
  & egemenlik (182), milletin (581), kalesidir (106), kayıtsız (103), şartsız (103), kaydü (46), şart (48), hakimiyet (35), anayasa (103), bila (33), temsilcileri (26), meclis (77), divanıdır (16), cumhuriyet (82), sofrasına (16), irade (67), mekanı (14), erdoğan (39), partisi (80), organları (15), evinde (16), ilkesinden (12), masası (11), türkiye (77), hakemliğine (36), devlet (59), türk (65), malını (14), padişahın (11), patron (12) \\[8pt]
\raggedright \textbf{Demands & Problems Node} \newline (459)
  & 1.0 & \textbf{1.1} & 0.9
  & milletin (547), zam (46), enflasyonu (41), derdini (34), fatura (33), hakkını (121), fukaranın (21), sırtına (64), ekmek (19), talebi (22), erdoğan (45), partisi (84), anasını (15), fakir (23), doları (17), fiyat (18), dem (20), sorunlarını (61), hukukunu (55), lira (50), sarayın (55), avro (11), gündemini (35), para (49), garantisi (14), siyasi (52), yoksulluğa (13), vatandaş (39), türkiye (66), pazar (12) \\[8pt]
\raggedright \textbf{Nationalism} \newline (330)
  & 1.0 & 0.8 & \textbf{1.1}
  & sevgisi (95), milletinin (248), yüreğinde (59), vatan (170), bayrak (143), şerefim (36), renklerini (41), ittifakı (115), türkiye (149), yıldızlı (31), bütündür (19), türk (113), gücümle (16), atatürk (99), gücünü (28), ülkenin (52), insanları (60), parti (76), kalbinde (15), devleti (64), beyaz (26), demokratlar (43), kırmızı (23), büyük (71), halk (48), mektubu (14), cumhuriyeti (62), tarafsızlıkla (28), güzel (67), yürekli (10) \\[8pt]
\raggedright \textbf{Service Node} \newline (119)
  & 0.7 & \textbf{1.3} & 0.9
  & millete (118), hizmet (67), zenginliğimizi (7), sofrası (6), siyaset (32), parasını (27), halk (32), cebini (6), memurları (11), iktidar (24), emeğini (4), terini (5), devletin (25), türkiye (26), partisi (22), başkanı (16), saygı (12), cepleri (3), kalbi (4), kadrolar (12), mütevazı (4), belediye (15), aracı (4), sadakatle (3), fikrinin (3), köylüleri (3), kahraman (4), cumhuriyet (18), erdoğan (7), çatısı (4) \\[8pt]
\raggedright \textbf{Antagonist: Erdoğan} \newline (1440)
  & 0.9 & 0.7 & \textbf{1.2}
  & milletin (1244), erdoğan (257), parti (268), vicdanına (128), yüzüne (48), başkan (166), aklıyla (32), savcı (39), yakasından (37), kuyruğu (28), yoksulluk (40), siyasi (136), iktidar (145), darbe (129), seçim (135), zam (37), fakir (30), karşısına (103), hakkını (113), devlet (142), çadır (29), alay (31), perişan (48), belediye (117), terör (37), türkiye (163), meydan (105), pazar (27), ülkenin (114), kayyum (26) \\[8pt]
\raggedright \textbf{Appeal to the Nation} \newline (433)
  & 0.8 & 0.8 & \textbf{1.2}
  & milletin (550), sesini (49), erdoğan (53), aziz (27), meşruiyet (21), takdiriyle (48), parti (87), seçim (72), başkan (64), gücümüzü (16), karşısına (55), sesi (20), programı (13), halk (60), türkiye (68), söz (56), iddia (12), meydan (42), huzurunda (30), darbe (40), cumhurbaşkanı (46), belediye (41), yetkiyi (34), ülkeyi (42), siyasi (46), savcı (9), iktidar (47), soruları (9), mesajı (10), talebi (10) \\[8pt]
\raggedright \textbf{Nation's Will} \newline (922)
  & 0.6 & 0.9 & \textbf{1.2}
  & milletin (834), iradesine (253), seçim (271), partisi (289), ferasetine (58), erdoğan (102), halk (168), iktidar (148), kararı (112), başkanı (125), demokrasi (152), oylarıyla (33), adayımı (77), belediye (106), gücünü (31), darbe (103), cumhurbaşkanı (107), saygı (98), siyasi (93), türkiye (123), mesajını (21), yanımda (20), iddianame (19), oyuyla (18), sağduyusuna (23), sandığa (63), hak (58), cunta (17), tokadı (16), cumhuriyet (89) \\[8pt]
\raggedright \textbf{State Node} \newline (350)
  & 0.6 & 0.4 & \textbf{1.5}
  & devlet (449), milletin (408), çıkarlarını (42), ajansı (40), karşısına (137), polis (35), evladı (63), kenan (24), kurşun (19), partisi (90), evren (23), özal (18), sever (18), erdoğan (35), tarafta (37), askere (39), anadolu (24), trt (15), kaymakamlarını (9), seçim (46), menfaati (10), bütünlüğü (10), başkanı (51), valileri (8), bağlı (12), türkiye (59), vatanına (27), yanındaydı (20), ülkenin (45), elleri (9) \\[8pt]
\raggedright \textbf{Peasant as the Master} \newline (136)
  & 0.4 & 0.5 & \textbf{1.5}
  & efendisi (159), köylü (89), ananı (46), çiftçi (114), milletin (159), tarım (13), cumhurbaşkanı (55), emekli (29), fiyatları (7), hayvancılıkla (6), perişan (12), narenciye (5), atatürk (37), esnafın (18), kemal (36), yozgat (6), mustafa (35), fındık (6), işçi (6), partisi (21), gazi (31), sonuncusu (11), karnı (5), yazıklar (6), türkiye (26), emeği (4), ülkenin (20), cambaza (3), ürünler (3), lira (14) \\[8pt]
\raggedright \textbf{Resistance Rhetoric & Imamoğlu} \newline (535)
  & 0.2 & 0.2 & \textbf{1.7}
  & milletin (581), gönlünde (122), partisi (234), santim (51), erdoğan (82), kelime (29), inatlaşılır (20), başkanı (88), gözünden (61), anketlerde (18), belediye (78), eksik (30), halk (89), karşısında (58), darbe (72), seçim (73), verene (20), adayı (53), girişimi (20), geriye (23), aday (25), iktidar (70), siyasi (62), ülkeyi (64), türkiye (76), görev (54), mücadele (43), cumhuriyet (63), işçi (12), butlan (8) \\[8pt]
\midrule
\raggedright \textit{Shared across clusters}
  & & &
  & türkiye (2339), meclisi (1812), partisi (1782), büyük (1546), devlet (1239), başkanı (1105), ittifakı (929), seçim (918), halk (877), siyasi (821), ülkenin (805), cumhuriyet (803), erdoğan (743), demokrasi (730), iktidar (710) \\
\end{longtable}